name: Deploy ke Freehostia
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil File dari GitHub
        uses: actions/checkout@v3

      - name: 2. Siapkan Mesin PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: 3. Bikin Folder Vendor (Ini yang bikin nyala!)
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: 3.5. Setup Node & Build Tailwind CSS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci || npm install
      - run: npm run build

      - name: 4. Kirim Semua File ke Freehostia
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 162.210.102.233
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /www/ukm.satta.web.id/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/.github/**
            README.md
            .env.example
            phpunit.xml
